### PR TITLE
Add self-hosted OS, delete event and more Step defaults

### PR DESCRIPTION
**Pull request by timbertson**
- added `On.delete` and corresponding `Delete` event type, which is kind of silly (it's `{}`) but I made it a real type for consistency and future compatibility
 - added `self-hosted` and `custom` `RunsOn`, the latter letting you specify arbitrary tags
 - Step: default all of `id` / `name` / `run` and `uses` to `None`

Aside: I wasn't sure how to keep the inline caches updated during development. I ended up running:

```
for f in *.dhall; do echo "$f"; dhall freeze --inplace "$f"; done
```

Not sure if there's a better option, I couldn't see anything in the Makefile. Personally I've been leaving digests off for local imports, and only freezing remote imports. If you're freezing at the toplevel, I don't know if freezing the individual modules is worth the diff noise / conflicts.

### CODE REVIEW

**Comment by timbertson** [comment]
> The imports under {types | steps | schemas defaults}.dhall are also freezed because they can also be imported separately.

I'm a bit confused by that. If you import them separately (say, by `let Push = https://raw.githubusercontent.com/.../schemas/events/Push.dhall`), then it makes sense for that import to be frozen. But that import will live in your own codebase (not in `github-actions-dhall`), so it isn't affected by the fact that `schemas.dhall` freezes it. Or am I misunderstanding something?

**Comment by regadas** [comment]
Hi @timbertson, yes you can import them directly and freeze would be on your own codebase. However, if the import you are using has other imports, if they are not freezed it means that when they get expanded they will need to be resolved again. By having them freezed you get all the niceties of semantic integrity checking plus caching.

After yesterdays comment I realize that I only do it a bit half way by only having the imports defined in `{package | types | steps | schemas defaults}.dhall` freezed (initially I based myself in `dhall-kubernetes`). I should actually freeze every import, which is what actually `Prelude` does.

**Comment by timbertson** [comment]
> However, if the import you are using has other imports, if they are not freezed it means that when they get expanded they will need to be resolved again.

What do you mean by "expanded"? Do you mean if they change? Or simply when the file you import imports another? Because if I freeze the toplevel import, like this:

```
https://raw.githubusercontent.com/regadas/github-actions-dhall/master/schemas.dhall sha256:e23064d43ac3eecdf3bfd45aa4e17758a5edb979f0cb611e344d80bdca418156
```

..then it doesn't matter for caching if the inner imports (to `./schemas/Job.dhall` etc) inside that file are frozen or not, because that `sha256` covers the fully-expanded contents, including any transitive imports.

**Comment by regadas** [comment]
> ..then it doesn't matter for caching if the inner imports (to ./schemas/Job.dhall etc) inside that file are frozen or not, because that sha256 covers the fully-expanded contents, including any transitive imports.

it actually matters if they are freezed or not! If the import is freezed it will be cached separately. Meaning that you can resolve it later if you are offline.

consider the following example:

a.dhall
```
let b = https://remote/b.dhall sha256:...

...
```

b.dhall
```
let c = ./c.dhall

...
```

after running `a.dhall` you will only see 1 hash entry in `.cache`. If you are offline this still works because `b` and it's contents are cached. But now try the following:

a.dhall
```
let b = https://remote/b.dhall sha256:...

let c = https://remote/c.dhall

...
```

you will see that if you try running `dhall freeze` you will not be able to resolve the import. If you want to try this out make sure you have `XDG_CACHE_HOME=.cache` and you don't have a global `.cache` otherwise it will fallback.

**Comment by timbertson-zd** [comment]
That's true, but it seems like a super niche use case - adding a new import of a sub-dependency which you have already cached, while offline. I don't think _any_ `dhall freeze` works offline, since it ignores digests in the file it's freezing.

For the most part, I imagine remote dependencies are added by writing / pasting the raw URL into source code, then running `dhall freeze`. In which case, it doesn't matter which sub-imports are cached, `dhall freeze` will result in a fully frozen set of imports.

**Comment by regadas** [comment]
> That's true, but it seems like a super niche use case 
I cant assume this plus makes resolution times "somewhat" faster.

`dhall freeze` I should have mentioned `dhall-to-yaml/json` because it works as you said, but anyway you get the point.

**Pull request merged**
