### PR TITLE
actions.cache: accept a list of file patterns to hash

### LINKED ISSUE #17: steps.cache should accept multiple patterns
The `hashFiles` function in the Github Actions expression language can support multiple patterns: https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#hashfiles

It would be nice for the cache step in this repo to support that also, by taking a `List Text` instead of a single `Text`. I started to prepare a PR for this but got lost in apparent duplication: what is the design intent between `steps/cache.dhall` and `steps/actions/cache.dhall`? `dhall hash` says that they're identical. Is one deprecated?

### PR DESCRIPTION
**Pull request by JackKelly-Bellroy**
Fixes #17

### CODE REVIEW

**Comment by JackKelly-Bellroy** [comment]
If you are happy with the way I have set up action argument schemas in #20 , I might do the same here because I find myself wanting to pass an `id` parameter to the `actions/cache` action (so I can skip steps on cache hit).

**Review by regadas — APPROVED** [review]
LGTM. Thanks @JackKelly-Bellroy (sorry for late review)

**Comment by regadas** [comment]
regarding the `id` I guess you could do:
```
GithubActions.steps.actions/cache
          { path = "PATH", key = "KEY", hashFile = ["**/files"] } // { id = Some "ID" } 
```

It's inline with how we would set it for other actions.

**Comment by JackKelly-Bellroy** [comment]
Re: `// { id = "foo" }`: I think the record-of-three-args is juuust small enough that not using schemas still feels okay, given that we can splice the fields we need into the record afterwards (unless there's some big consistency push later to give everything a schema or somesuch). Thanks for the tip.

**Pull request merged**
