### PR TITLE
Add support for matrix-os to runson type

### PR DESCRIPTION
**Pull request by ggilmore**
Fixes https://github.com/regadas/github-actions-dhall/issues/8

Used in https://github.com/ggilmore/asdf-comby/blob/4c6e8e1e329e8ce76e6b137ef439b12161ab787f/ci/dhall/jobs/asdf-plugin-test.dhall#L12

### CODE REVIEW

**Comment by ggilmore** [comment]
@regadas I wasn't able to update all the hashes because the URL is hard coded for this repo in some of the examples

**Review by regadas — COMMENTED** [review]
Thank you for this @ggilmore (sorry for the late reply). Do you mind rebasing this?

**Comment by ggilmore** [comment]
@regadas I merged in the latest commits. You'll still have to update the sha256 hashes in your branch once this is merged to `master`.

**Comment by ggilmore** [comment]
Also as a side note @regadas, you might be interested in how I setup things in my personal template repository: https://github.com/ggilmore/kickstart 

Among other things, it has a CI pipeline / scripts for ensuring that all the dhall code committed is formated/linted/typechecked/frozen. Having a workflow similar to this one might make it easier to manage contributions (ensuring that the basics are checked for each PR).

**Review by regadas — APPROVED** [review]

**Comment by regadas** [comment]
Thank you @ggilmore!

> Also as a side note @regadas, you might be interested in how I setup things in my personal template repository: ggilmore/kickstart

Nice I'll have a look!

> Among other things, it has a CI pipeline / scripts for ensuring that all the dhall code committed is formated/linted/typechecked/frozen. Having a workflow similar to this one might make it easier to manage contributions (ensuring that the basics are checked for each PR).

Yea, having something like that would be great! Not sure if you would be open to contribute that back?

Thank you again!

**Pull request merged**
